Some bug fixes

diff --git a/.github/workflows/get id.yml b/.github/workflows/get id.yml
--- a/.github/workflows/get id.yml
+++ b/.github/workflows/get id.yml
@@ -11,15 +11,22 @@ jobs:
     runs-on: windows-latest  # Use the latest version of Windows
 
     steps:
-      - name: Get Job ID from GH API
-        id: get-job-id
+      - name: Parse job_id
+        id: request
         env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
+          INPUT_REPOSITORY: ${{ inputs.repository }}
+          INPUT_RUN_ID: ${{ inputs.run_id }}
+          INPUT_JOB_NAME: ${{ inputs.job_name }}
+          INPUT_PER_PAGE: ${{ inputs.per_page }}
+          GITHUB_BASEURL: ${{ github.api_url }}
+        shell: bash
         run: |
-          jobs=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs)
-          echo $jobs
-
-      - name: Display Job ID
-        run: |
-          echo Job ID: ${{ steps.get-job-id.outputs.job_id }}
-          echo My full job URL is ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ steps.get-job-id.outputs.job_id }}
+          GITHUB_API="/repos/${INPUT_REPOSITORY:-${GITHUB_REPOSITORY}}/actions/runs/${INPUT_RUN_ID:-${GITHUB_RUN_ID}}/jobs"
+          JOBINFO="$(curl --get -Ss -H "Authorization: Bearer ${INPUT_GITHUB_TOKEN}" -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "${GITHUB_BASEURL}${GITHUB_API}?per_page=${INPUT_PER_PAGE:-30}")"
+          echo "${JOBINFO}" | grep "Resource not accessible by integration" &&  exit 1
+          TOTAL_COUNT="$(echo "${JOBINFO}" | jq -r .total_count)"
+          eval "$(echo ${JOBINFO} | jq -r --arg job_name "${INPUT_JOB_NAME}" '.jobs | map(select(.name == $job_name)) | .[0] | @sh "JOB_ID=\(.id) HTML_URL=\(.html_url)"')"
+          echo ${JOB_ID} | grep "null" > /dev/null && echo "parse error, job_id is ${JOB_ID} and total_count is ${TOTAL_COUNT}. 'job_name' or 'per_page' might be wrong. See https://github.com/Tiryoh/gha-jobid-action/blob/main/README.md#inputs" && exit 1
+          echo "job_id=${JOB_ID}" >> $GITHUB_OUTPUT
+          echo "html_url=${HTML_URL}" >> $GITHUB_OUTPUT
